# Generated by Django 3.2.25 on 2025-01-15 10:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='definition',
            field=models.JSONField(default=dict, help_text='Complete workflow definition including nodes and connections'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='execution_context',
            field=models.JSONField(blank=True, default=dict, help_text='Additional context for execution'),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='input_data',
            field=models.JSONField(blank=True, default=dict, help_text='Input data for this node'),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='output_data',
            field=models.JSONField(blank=True, default=dict, help_text='Output data from this node'),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='error_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed error information'),
        ),
    ]