# Generated by Django 3.2.25 on 2025-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0002_complete_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeexecution',
            name='error_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='input_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='nodeexecution',
            name='output_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='execution_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
